version: "3.1"

services:
  backend-myhome.app:
    container_name: backend-myhome.app
    image: backend-myhome:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js
    environment:
      - PORT=8080
    networks:
      - local-dev-network
    depends_on:
      - backend-myhome.pg
  backend-myhome.pg:
    container_name: backend-myhome.pg
    image: postgres:latest
    volumes:
      - /shared_folder/postgresql:/var/lib/postgresql
      - ./db/script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=backend-myhome.pg
      - POSTGRES_USER=myhome
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=myhome
      - POSTGRES_PORT=5432
    networks:
      - local-dev-network
networks:
  local-dev-network:
    external: false